In [66]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import tree

In [67]:
data = pd.read_csv('./Resources/behavioral_revised_data_final.csv')
data.head()

,State,State Code,Sex,Marital Status,Age,Race,Education,Weight(lbs),Height(ft),Income,...,Physical Activity/Day(mints),Smoking,Alcohol/Day,BMI,Blood Pressure,Cholestrol,Heart Disease,Stroke,Cancer,Diabetes
0,Alabama,AL,Female,Widowed,70-74,White only,High School,128.0,4.99980,20000-25000,...,30.0,Every day,2.0,Overweight,Yes,Yes,No,No,No,No
1,Alabama,AL,Male,Married,>80,White only,College 4yrs,172.0,5.83310,>75000,...,40.0,Not at all,1.0,Normal Weight,No,No,No,No,No,Yes
2,Alabama,AL,Male,Married,50-54,White only,College 3yrs,135.0,5.33312,35000-50000,...,308.0,Every day,1.0,Normal Weight,No,No,No,No,No,Yes
3,Alabama,AL,Male,Married,35-39,White only,College 3yrs,190.0,5.99976,15000-20000,...,20.0,Every day,1.0,Overweight,No,No,No,No,No,No
4,Alabama,AL,Male,Married,65-69,White only,College 4yrs,212.0,5.91643,Refused,...,150.0,Not at all,1.0,Overweight,Yes,Yes,Yes,Yes,No,No

In [68]:
len(data)

55729

In [69]:
# columns
data.columns

Index(['State', 'State Code', 'Sex', 'Marital Status', 'Age', 'Race',
       'Education', 'Weight(lbs)', 'Height(ft)', 'Income', 'Vegetables/Day',
       'Fruits/Day', 'Physical Activity/Day(mints)', 'Smoking', 'Alcohol/Day',
       'BMI', 'Blood Pressure', 'Cholestrol', 'Heart Disease', 'Stroke',
       'Cancer', 'Diabetes'],
      dtype='object')

In [70]:
#renaming the columns 
data.columns = ['state', 'state_code', 'sex', 'marital_status', 'age', 'race',
       'education', 'weight', 'height', 'income', 'vegetables_day',
       'fruits_day', 'physical_ctivity', 'smoking', 'alcohol_day',
       'bmi', 'blood_pressure', 'cholestrol', 'heart_disease', 'stroke',
       'cancer', 'diabetes']

In [71]:
data.head()

,state,state_code,sex,marital_status,age,race,education,weight,height,income,...,physical_ctivity,smoking,alcohol_day,bmi,blood_pressure,cholestrol,heart_disease,stroke,cancer,diabetes
0,Alabama,AL,Female,Widowed,70-74,White only,High School,128.0,4.99980,20000-25000,...,30.0,Every day,2.0,Overweight,Yes,Yes,No,No,No,No
1,Alabama,AL,Male,Married,>80,White only,College 4yrs,172.0,5.83310,>75000,...,40.0,Not at all,1.0,Normal Weight,No,No,No,No,No,Yes
2,Alabama,AL,Male,Married,50-54,White only,College 3yrs,135.0,5.33312,35000-50000,...,308.0,Every day,1.0,Normal Weight,No,No,No,No,No,Yes
3,Alabama,AL,Male,Married,35-39,White only,College 3yrs,190.0,5.99976,15000-20000,...,20.0,Every day,1.0,Overweight,No,No,No,No,No,No
4,Alabama,AL,Male,Married,65-69,White only,College 4yrs,212.0,5.91643,Refused,...,150.0,Not at all,1.0,Overweight,Yes,Yes,Yes,Yes,No,No

In [72]:
data.dropna(axis='columns')

,state,state_code,sex,marital_status,age,race,education,weight,height,income,...,physical_ctivity,smoking,alcohol_day,bmi,blood_pressure,cholestrol,heart_disease,stroke,cancer,diabetes
0,Alabama,AL,Female,Widowed,70-74,White only,High School,128.0,4.99980,20000-25000,...,3.000000e+01,Every day,2.0,Overweight,Yes,Yes,No,No,No,No
1,Alabama,AL,Male,Married,>80,White only,College 4yrs,172.0,5.83310,>75000,...,4.000000e+01,Not at all,1.0,Normal Weight,No,No,No,No,No,Yes
2,Alabama,AL,Male,Married,50-54,White only,College 3yrs,135.0,5.33312,35000-50000,...,3.080000e+02,Every day,1.0,Normal Weight,No,No,No,No,No,Yes
3,Alabama,AL,Male,Married,35-39,White only,College 3yrs,190.0,5.99976,15000-20000,...,2.000000e+01,Every day,1.0,Overweight,No,No,No,No,No,No
4,Alabama,AL,Male,Married,65-69,White only,College 4yrs,212.0,5.91643,Refused,...,1.500000e+02,Not at all,1.0,Overweight,Yes,Yes,Yes,Yes,No,No
5,Alabama,AL,Female,Never married,55-59,Black only,College 4yrs,130.0,5.49978,15000-20000,...,3.000000e+01,Every day,1.0,Normal Weight,No,Yes,No,No,Yes,No
6,Alabama,AL,Male,Divorced,65-69,Black only,Junior High,157.0,5.49978,Donâ€™t know/Not sure,...,7.710865e-80,Every day,2.0,Overweight,No,Yes,No,No,No,No
7,Alabama,AL,Female,Never married,50-54,Black only,Junior High,135.0,5.49978,15000-20000,...,8.571429e+00,Some days,3.0,Normal Weight,Yes,No,No,No,No,No
8,Alabama,AL,Male,Divorced,70-74,White only,College 4yrs,260.0,6.16642,35000-50000,...,1.600000e+01,Not at all,1.0,Obese,Yes,Yes,Yes,No,Yes,No
9,Alabama,AL,Male,Married,55-59,White only,College 3yrs,215.0,6.08309,50000-75000,...,2.571429e+01,Not at all,1.0,Overweight,No,Yes,No,No,No,No
10,Alabama,AL,Male,Married,75-79,White only,College 3yrs,180.0,5.66644,25000-35000,...,4.800000e+02,Not at all,3.0,Overweight,Yes,Yes,No,No,No,No
11,Alabama,AL,Male,Married,55-59,White only,College 3yrs,230.0,5.58311,15000-20000,...,2.200000e+01,Not at all,3.0,Obese,Yes,Yes,No,No,No,No
12,Alabama,AL,Male,Separated,70-74,White only,College 4yrs,195.0,5.99976,15000-20000,...,1.885714e+02,Not at all,5.0,Overweight,Yes,Yes,No,No,No,No
13,Alabama,AL,Female,Divorced,65-69,Other race only,High School,162.0,5.41645,50000-75000,...,3.000000e+01,Some days,3.0,Overweight,No,No,No,No,Yes,No
14,Alabama,AL,Male,Married,70-74,White only,College 3yrs,190.0,5.66644,50000-75000,...,1.014286e+02,Not at all,5.0,Overweight,Yes,Yes,No,No,No,Yes
15,Alabama,AL,Male,Divorced,60-64,White only,College 4yrs,170.0,5.99976,35000-50000,...,8.571429e+01,Not at all,1.0,Normal Weight,Yes,Yes,No,No,Yes,No
16,Alabama,AL,Male,Divorced,50-54,White only,High School,250.0,6.16642,25000-35000,...,1.228571e+01,Every day,4.0,Obese,Yes,Yes,No,No,No,Yes
17,Alabama,AL,Male,Widowed,75-79,White only,College 3yrs,190.0,5.91643,Refused,...,5.714286e+01,Not at all,1.0,Overweight,Yes,Yes,Yes,No,No,No
18,Alabama,AL,Male,Separated,30-34,White only,College 3yrs,205.0,5.99976,35000-50000,...,8.142857e+01,Some days,1.0,Overweight,No,No,No,No,No,No
19,Alabama,AL,Female,Married,70-74,White only,College 4yrs,160.0,5.66644,50000-75000,...,4.928571e+01,Not at all,2.0,Normal Weight,No,No,Yes,No,No,No
20,Alabama,AL,Male,Divorced,75-79,White only,College 3yrs,162.0,5.66644,25000-35000,...,7.710865e-80,Every day,1.0,Normal Weight,Yes,Yes,Yes,Yes,No,No
21,Alabama,AL,Female,Married,75-79,White only,College 4yrs,140.0,5.49978,>75000,...,1.200000e+02,Not at all,1.0,Normal Weight,Yes,Yes,No,No,Yes,No
22,Alabama,AL,Male,Married,40-44,White only,College 4yrs,185.0,5.74977,>75000,...,5.714286e+00,Not at all,3.0,Overweight,No,Yes,No,No,No,No
23,Alabama,AL,Female,Widowed,70-74,White only,College 3yrs,120.0,4.99980,Donâ€™t know/Not sure,...,1.371429e+02,Not at all,1.0,Normal Weight,No,No,No,No,No,No
24,Alabama,AL,Male,Married,55-59,White only,College 3yrs,195.0,5.74977,>75000,...,4.714286e+01,Not at all,6.0,Overweight,Yes,Yes,No,No,No,Yes
25,Alabama,AL,Female,Married,70-74,White only,College 3yrs,140.0,5.24979,Refused,...,3.000000e+01,Not at all,1.0,Normal Weight,No,Yes,No,No,No,No
26,Alabama,AL,Female,Widowed,>80,White only,High School,131.0,5.49978,>75000,...,1.200000e+01,Not at all,1.0,Normal Weight,No,Yes,Yes,No,No,No
27,Alabama,AL,Female,Married,60-64,White only,High School,130.0,5.41645,>75000,...,2.185714e+01,Not at all,1.0,Normal Weight,No,No,No,No,No,No
28,Alabama,AL,Female,Married,55-59,Black only,Elementary,150.0,5.16646,20000-25000,...,7.710865e-80,Not at all,6.0,Overweight,Yes,Yes,No,No,Yes,Yes
29,Alabama,AL,Male,Married,65-69,Black only,College 3yrs,200.0,5.83310,35000-50000,...,8.571429e+00,Not at all,1.0,Overweight,Yes,Yes,No,No,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55699,Puerto Rico,PR,Female,A member of an unmarried couple,30-34,Hispanic,College 4yrs,199.0,5.66644,>75000,...,2.571429e+01,Not at all,1.0,Obese,Yes,Yes,No,No,No,No
55700,Puerto Rico,PR,Male,Never married,18-24,Hispanic,College 3yrs,225.0,5.83310,25000-35000,...,7.714286e+01,Not at all,2.0,Obese,No,No,No,No,No,No
55701,Puerto Rico,PR,Female,A member of an unmarried couple,30-34,Hispanic,College 4yrs,200.0,5.58311,50000-75000,...,3.428571e+01,Not at all,1.0,Obese,No,No,No,No,No,No
55702,Puerto Rico,PR,Male,Never married,18-24,Hispanic,College 4yrs,238.0,6.08309,35000-50000,...,1.088571e+02,Every day,5.0,Obese,No,No,No,No,No,No
55703,Puerto Rico,PR,Female,Married,40-44,Hispanic,College 4yrs,190.0,5.49978,50000-75000,...,1.285714e+01,Not at all,3.0,Obese,Yes,No,No,No,No,No
55704,Puerto Rico,PR,Male,Married,55-59,Hispanic,College 3yrs,240.0,5.91643,20000-25000,...,8.000000e+00,Not at all,6.0,Obese,Yes,No,No,No,No,No
55705,Puerto Rico,PR,Male,Married,70-74,Hispanic,Elementary,129.0,5.16646,15000-20000,...,1.428571e+01,Some days,2.0,Normal Weight,Yes,Yes,No,No,No,No
55706,Puerto Rico,PR,Female,A member of an unmarried couple,35-39,Hispanic,High School,200.0,5.49978,25000-35000,...,2.571429e+01,Every day,3.0,Obese,Yes,No,No,No,No,No
55707,Puerto Rico,PR,Male,A member of an unmarried couple,45-49,Hispanic,College 4yrs,160.0,5.49978,25000-35000,...,8.571429e+01,Every day,10.0,Overweight,No,No,No,No,No,No
55708,Puerto Rico,PR,Male,Married,50-54,Hispanic,College 3yrs,195.0,5.91643,20000-25000,...,1.714286e+01,Some days,6.0,Overweight,Yes,No,Yes,No,No,Yes
55709,Puerto Rico,PR,Female,Married,25-29,Hispanic,College 4yrs,200.0,5.24979,25000-35000,...,8.571429e+00,Some days,3.0,Obese,No,No,No,No,No,No
55710,Puerto Rico,PR,Male,Divorced,40-44,Hispanic,College 4yrs,210.0,5.58311,50000-75000,...,2.571429e+01,Not at all,4.0,Obese,No,No,No,Yes,No,No
55711,Puerto Rico,PR,Male,Married,60-64,Hispanic,High School,190.0,5.74977,25000-35000,...,4.285714e+01,Not at all,2.0,Overweight,No,No,No,No,No,No
55712,Puerto Rico,PR,Male,Married,60-64,Hispanic,College 4yrs,250.0,5.74977,20000-25000,...,8.571429e+00,Not at all,2.0,Obese,Yes,Yes,No,No,No,Yes
55713,Puerto Rico,PR,Female,Never married,35-39,Hispanic,College 3yrs,164.0,5.49978,35000-50000,...,2.571429e+01,Every day,3.0,Overweight,No,No,No,No,No,No
55714,Puerto Rico,PR,Male,Never married,18-24,Hispanic,High School,220.0,5.99976,Refused,...,4.285714e+01,Some days,8.0,Overweight,Yes,No,No,No,No,No
55715,Puerto Rico,PR,Male,Married,40-44,Hispanic,College 4yrs,196.0,5.74977,25000-35000,...,3.200000e+01,Not at all,1.0,Overweight,No,No,No,No,No,No
55716,Puerto Rico,PR,Female,Married,55-59,Hispanic,College 3yrs,172.0,5.58311,35000-50000,...,7.285714e+01,Not at all,1.0,Overweight,Yes,Yes,No,No,No,No
55717,Puerto Rico,PR,Male,Married,60-64,Hispanic,College 4yrs,175.0,5.74977,35000-50000,...,4.285714e+01,Not at all,4.0,Overweight,No,No,No,No,No,No
55718,Puerto Rico,PR,Male,Never married,30-34,Hispanic,College 4yrs,140.0,5.41645,35000-50000,...,6.428571e+01,Not at all,2.0,Normal Weight,No,Yes,No,No,No,No
55719,Puerto Rico,PR,Female,Divorced,70-74,Hispanic,College 3yrs,194.0,5.58311,20000-25000,...,2.142857e+01,Not at all,2.0,Obese,Yes,Yes,Yes,No,No,No
55720,Puerto Rico,PR,Male,Married,55-59,Hispanic,College 3yrs,216.0,5.74977,25000-35000,...,1.714286e+01,Not at all,6.0,Obese,Yes,Yes,No,No,No,Yes
55721,Puerto Rico,PR,Female,Married,55-59,Hispanic,High School,125.0,5.16646,35000-50000,...,6.142857e+00,Not at all,1.0,Normal Weight,No,Yes,No,No,No,No
55722,Puerto Rico,PR,Female,Divorced,60-64,Hispanic,College 4yrs,170.0,5.49978,>75000,...,9.285714e+01,Not at all,2.0,Overweight,No,No,No,No,No,No
55723,Puerto Rico,PR,Male,A member of an unmarried couple,40-44,Hispanic,College 3yrs,175.0,5.74977,35000-50000,...,9.428571e+00,Not at all,10.0,Overweight,Yes,No,No,No,No,No
55724,Puerto Rico,PR,Male,Widowed,55-59,Hispanic,College 4yrs,174.0,5.91643,>75000,...,1.200000e+02,Not at all,1.0,Normal Weight,No,Yes,No,No,No,No
55725,Puerto Rico,PR,Male,Married,35-39,Hispanic,High School,250.0,6.24975,20000-25000,...,1.800000e+01,Not at all,3.0,Obese,Yes,No,No,No,No,Yes
55726,Puerto Rico,PR,Male,Married,65-69,Hispanic,College 4yrs,210.0,5.33312,>75000,...,6.857143e+01,Not at all,10.0,Obese,Yes,No,No,No,No,Yes
55727,Puerto Rico,PR,Male,Married,50-54,Hispanic,College 4yrs,250.0,5.66644,>75000,...,4.000000e+00,Not at all,4.0,Obese,Yes,No,No,No,No,No
55728,Puerto Rico,PR,Female,A member of an unmarried couple,30-34,Hispanic,College 4yrs,105.0,5.33312,15000-20000,...,3.200000e+01,Every day,1.0,Underweight,No,No,No,No,No,No

In [73]:
# dropping 'refused' and ''DonÂ´t Know/Not Sure' from all rows. 
for col in data.columns:
    data = data[data[col]!="Refused"]
    data = data[data[col]!="Don't Know/Not Sure"]
    data = data[data[col]!="Donâ€™t know/Not sure"]
    data = data[data[col]!="DonÂ´t know/Not Sure"]
    data = data[data[col]!="Donâ€™t know/Not sure/Refused"]
    data = data[data[col]!="Donâ€™t know/Not Sure"]

/Users/azizkoyuncu/anaconda3/lib/python3.7/site-packages/pandas/core/ops.py:1649: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)

In [74]:
data.head()

,state,state_code,sex,marital_status,age,race,education,weight,height,income,...,physical_ctivity,smoking,alcohol_day,bmi,blood_pressure,cholestrol,heart_disease,stroke,cancer,diabetes
0,Alabama,AL,Female,Widowed,70-74,White only,High School,128.0,4.99980,20000-25000,...,30.0,Every day,2.0,Overweight,Yes,Yes,No,No,No,No
1,Alabama,AL,Male,Married,>80,White only,College 4yrs,172.0,5.83310,>75000,...,40.0,Not at all,1.0,Normal Weight,No,No,No,No,No,Yes
2,Alabama,AL,Male,Married,50-54,White only,College 3yrs,135.0,5.33312,35000-50000,...,308.0,Every day,1.0,Normal Weight,No,No,No,No,No,Yes
3,Alabama,AL,Male,Married,35-39,White only,College 3yrs,190.0,5.99976,15000-20000,...,20.0,Every day,1.0,Overweight,No,No,No,No,No,No
5,Alabama,AL,Female,Never married,55-59,Black only,College 4yrs,130.0,5.49978,15000-20000,...,30.0,Every day,1.0,Normal Weight,No,Yes,No,No,Yes,No

In [75]:
data['blood_pressure'].value_counts()

No            27860
Yes           20748
Borderline      624
Name: blood_pressure, dtype: int64

In [76]:

Y = data['blood_pressure'].copy()
Y.value_counts(normalize=True)
Y = pd.get_dummies(Y,drop_first=False)
Y = Y.rename(columns={"Yes":"blood_pressure"})
del Y["No"]
del Y["Borderline"]
Y.head()

   blood_pressure
0               1
1               0
2               0
3               0
5               0

In [77]:
Y['blood_pressure'].value_counts(normalize=True)

0    0.578567
1    0.421433
Name: blood_pressure, dtype: float64

In [78]:
X = data.copy()
del X['blood_pressure']
del X['state']
del X['state_code']

In [79]:
# Ordinal encode age
age_map = {
    '18-24':0,
    '25-29':1,
    '30-34':2,
    '35-39':3,
    '40-44':4,
    '45-49':5,
    '50-54':6,
    '55-59':7,
    '60-64':8,
    '65-69':9,
    '70-74':10,
    '75-79':11,
    '>80':12}

X = X.replace({'age':age_map})
X['age'] = X['age'].astype(int)

In [80]:
# Ordinal encode age
inc_map = {
    '< 10000':0,
    '10000-15000':1,
    '15000-20000':2,
    '20000-25000':2,
    '25000-35000':3,
    '35000-50000':4,
    '50000-75000':5,
    ' >75000':6}
X = X.replace({'income':inc_map})
X['income'] = X['income'].astype(int)
X

,sex,marital_status,age,race,education,weight,height,income,vegetables_day,fruits_day,physical_ctivity,smoking,alcohol_day,bmi,cholestrol,heart_disease,stroke,cancer,diabetes
0,Female,Widowed,10,White only,High School,128.0,4.99980,2,2.67,0.34,3.000000e+01,Every day,2.0,Overweight,Yes,No,No,No,No
1,Male,Married,12,White only,College 4yrs,172.0,5.83310,6,1.83,1.67,4.000000e+01,Not at all,1.0,Normal Weight,No,No,No,No,Yes
2,Male,Married,6,White only,College 3yrs,135.0,5.33312,4,0.97,0.00,3.080000e+02,Every day,1.0,Normal Weight,No,No,No,No,Yes
3,Male,Married,3,White only,College 3yrs,190.0,5.99976,2,1.42,4.29,2.000000e+01,Every day,1.0,Overweight,No,No,No,No,No
5,Female,Never married,7,Black only,College 4yrs,130.0,5.49978,2,1.86,5.00,3.000000e+01,Every day,1.0,Normal Weight,Yes,No,No,Yes,No
7,Female,Never married,6,Black only,Junior High,135.0,5.49978,2,2.57,1.29,8.571429e+00,Some days,3.0,Normal Weight,No,No,No,No,No
8,Male,Divorced,10,White only,College 4yrs,260.0,6.16642,4,4.00,0.37,1.600000e+01,Not at all,1.0,Obese,Yes,Yes,No,Yes,No
9,Male,Married,7,White only,College 3yrs,215.0,6.08309,5,1.00,2.00,2.571429e+01,Not at all,1.0,Overweight,Yes,No,No,No,No
10,Male,Married,11,White only,College 3yrs,180.0,5.66644,3,1.04,0.44,4.800000e+02,Not at all,3.0,Overweight,Yes,No,No,No,No
11,Male,Married,7,White only,College 3yrs,230.0,5.58311,2,0.39,1.00,2.200000e+01,Not at all,3.0,Obese,Yes,No,No,No,No
12,Male,Separated,10,White only,College 4yrs,195.0,5.99976,2,3.40,0.43,1.885714e+02,Not at all,5.0,Overweight,Yes,No,No,No,No
13,Female,Divorced,9,Other race only,High School,162.0,5.41645,5,2.57,0.67,3.000000e+01,Some days,3.0,Overweight,No,No,No,Yes,No
14,Male,Married,10,White only,College 3yrs,190.0,5.66644,5,1.07,1.00,1.014286e+02,Not at all,5.0,Overweight,Yes,No,No,No,Yes
15,Male,Divorced,8,White only,College 4yrs,170.0,5.99976,4,3.43,7.00,8.571429e+01,Not at all,1.0,Normal Weight,Yes,No,No,Yes,No
16,Male,Divorced,6,White only,High School,250.0,6.16642,3,1.76,0.26,1.228571e+01,Every day,4.0,Obese,Yes,No,No,No,Yes
18,Male,Separated,2,White only,College 3yrs,205.0,5.99976,4,1.29,2.00,8.142857e+01,Some days,1.0,Overweight,No,No,No,No,No
19,Female,Married,10,White only,College 4yrs,160.0,5.66644,5,3.52,3.00,4.928571e+01,Not at all,2.0,Normal Weight,No,Yes,No,No,No
20,Male,Divorced,11,White only,College 3yrs,162.0,5.66644,3,0.71,0.43,7.710865e-80,Every day,1.0,Normal Weight,Yes,Yes,Yes,No,No
21,Female,Married,11,White only,College 4yrs,140.0,5.49978,6,3.34,1.13,1.200000e+02,Not at all,1.0,Normal Weight,Yes,No,No,Yes,No
22,Male,Married,4,White only,College 4yrs,185.0,5.74977,6,1.86,1.29,5.714286e+00,Not at all,3.0,Overweight,Yes,No,No,No,No
24,Male,Married,7,White only,College 3yrs,195.0,5.74977,6,1.70,0.43,4.714286e+01,Not at all,6.0,Overweight,Yes,No,No,No,Yes
26,Female,Widowed,12,White only,High School,131.0,5.49978,6,1.43,1.57,1.200000e+01,Not at all,1.0,Normal Weight,Yes,Yes,No,No,No
27,Female,Married,8,White only,High School,130.0,5.41645,6,1.59,2.00,2.185714e+01,Not at all,1.0,Normal Weight,No,No,No,No,No
28,Female,Married,7,Black only,Elementary,150.0,5.16646,2,0.56,0.58,7.710865e-80,Not at all,6.0,Overweight,Yes,No,No,Yes,Yes
29,Male,Married,9,Black only,College 3yrs,200.0,5.83310,4,2.29,1.13,8.571429e+00,Not at all,1.0,Overweight,Yes,No,No,Yes,Yes
30,Male,Married,9,White only,College 3yrs,220.0,5.74977,6,1.71,0.13,2.142857e+00,Not at all,3.0,Obese,No,No,No,No,Yes
31,Female,Married,6,White only,College 4yrs,120.0,5.24979,6,1.50,0.90,3.857143e+01,Not at all,1.0,Normal Weight,No,No,No,No,No
32,Male,Never married,4,White only,College 4yrs,240.0,6.41641,6,2.86,2.00,2.100000e+02,Not at all,3.0,Overweight,Yes,No,No,No,No
34,Male,Married,9,Other race only,College 3yrs,155.0,5.58311,4,1.83,1.33,6.428571e+01,Not at all,6.0,Normal Weight,Yes,No,No,No,No
35,Female,Divorced,5,Black only,College 4yrs,165.0,5.16646,5,2.26,2.00,7.714286e+01,Not at all,5.0,Obese,Yes,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55698,Male,Separated,6,Hispanic,High School,235.0,5.74977,1,2.14,0.86,1.028571e+02,Every day,6.0,Obese,No,No,No,No,No
55699,Female,A member of an unmarried couple,2,Hispanic,College 4yrs,199.0,5.66644,6,6.00,3.00,2.571429e+01,Not at all,1.0,Obese,Yes,No,No,No,No
55700,Male,Never married,0,Hispanic,College 3yrs,225.0,5.83310,3,1.29,1.16,7.714286e+01,Not at all,2.0,Obese,No,No,No,No,No
55701,Female,A member of an unmarried couple,2,Hispanic,College 4yrs,200.0,5.58311,5,3.07,0.17,3.428571e+01,Not at all,1.0,Obese,No,No,No,No,No
55702,Male,Never married,0,Hispanic,College 4yrs,238.0,6.08309,4,1.43,0.00,1.088571e+02,Every day,5.0,Obese,No,No,No,No,No
55703,Female,Married,4,Hispanic,College 4yrs,190.0,5.49978,5,1.43,0.43,1.285714e+01,Not at all,3.0,Obese,No,No,No,No,No
55704,Male,Married,7,Hispanic,College 3yrs,240.0,5.91643,2,0.79,0.43,8.000000e+00,Not at all,6.0,Obese,No,No,No,No,No
55705,Male,Married,10,Hispanic,Elementary,129.0,5.16646,2,1.72,0.98,1.428571e+01,Some days,2.0,Normal Weight,Yes,No,No,No,No
55706,Female,A member of an unmarried couple,3,Hispanic,High School,200.0,5.49978,3,0.29,2.00,2.571429e+01,Every day,3.0,Obese,No,No,No,No,No
55707,Male,A member of an unmarried couple,5,Hispanic,College 4yrs,160.0,5.49978,3,3.07,2.00,8.571429e+01,Every day,10.0,Overweight,No,No,No,No,No
55708,Male,Married,6,Hispanic,College 3yrs,195.0,5.91643,2,1.43,0.29,1.714286e+01,Some days,6.0,Overweight,No,Yes,No,No,Yes
55709,Female,Married,1,Hispanic,College 4yrs,200.0,5.24979,3,4.57,0.14,8.571429e+00,Some days,3.0,Obese,No,No,No,No,No
55710,Male,Divorced,4,Hispanic,College 4yrs,210.0,5.58311,5,1.74,0.86,2.571429e+01,Not at all,4.0,Obese,No,No,Yes,No,No
55711,Male,Married,8,Hispanic,High School,190.0,5.74977,3,0.00,0.88,4.285714e+01,Not at all,2.0,Overweight,No,No,No,No,No
55712,Male,Married,8,Hispanic,College 4yrs,250.0,5.74977,2,1.44,1.42,8.571429e+00,Not at all,2.0,Obese,Yes,No,No,No,Yes
55713,Female,Never married,3,Hispanic,College 3yrs,164.0,5.49978,4,1.51,1.00,2.571429e+01,Every day,3.0,Overweight,No,No,No,No,No
55715,Male,Married,4,Hispanic,College 4yrs,196.0,5.74977,3,1.36,0.80,3.200000e+01,Not at all,1.0,Overweight,No,No,No,No,No
55716,Female,Married,7,Hispanic,College 3yrs,172.0,5.58311,4,3.42,3.00,7.285714e+01,Not at all,1.0,Overweight,Yes,No,No,No,No
55717,Male,Married,8,Hispanic,College 4yrs,175.0,5.74977,4,1.29,5.00,4.285714e+01,Not at all,4.0,Overweight,No,No,No,No,No
55718,Male,Never married,2,Hispanic,College 4yrs,140.0,5.41645,4,1.71,0.03,6.428571e+01,Not at all,2.0,Normal Weight,Yes,No,No,No,No
55719,Female,Divorced,10,Hispanic,College 3yrs,194.0,5.58311,2,2.28,1.14,2.142857e+01,Not at all,2.0,Obese,Yes,Yes,No,No,No
55720,Male,Married,7,Hispanic,College 3yrs,216.0,5.74977,3,3.43,2.00,1.714286e+01,Not at all,6.0,Obese,Yes,No,No,No,Yes
55721,Female,Married,7,Hispanic,High School,125.0,5.16646,4,2.28,0.71,6.142857e+00,Not at all,1.0,Normal Weight,Yes,No,No,No,No
55722,Female,Divorced,8,Hispanic,College 4yrs,170.0,5.49978,6,1.39,0.00,9.285714e+01,Not at all,2.0,Overweight,No,No,No,No,No
55723,Male,A member of an unmarried couple,4,Hispanic,College 3yrs,175.0,5.74977,4,1.06,0.29,9.428571e+00,Not at all,10.0,Overweight,No,No,No,No,No
55724,Male,Widowed,7,Hispanic,College 4yrs,174.0,5.91643,6,1.37,1.71,1.200000e+02,Not at all,1.0,Normal Weight,Yes,No,No,No,No
55725,Male,Married,3,Hispanic,High School,250.0,6.24975,2,3.01,1.83,1.800000e+01,Not at all,3.0,Obese,No,No,No,No,Yes
55726,Male,Married,9,Hispanic,College 4yrs,210.0,5.33312,6,1.83,1.21,6.857143e+01,Not at all,10.0,Obese,No,No,No,No,Yes
55727,Male,Married,6,Hispanic,College 4yrs,250.0,5.66644,6,1.44,0.85,4.000000e+00,Not at all,4.0,Obese,No,No,No,No,No
55728,Female,A member of an unmarried couple,2,Hispanic,College 4yrs,105.0,5.33312,2,2.84,1.17,3.200000e+01,Every day,1.0,Underweight,No,No,No,No,No

In [81]:
X['income'].value_counts()

6    20501
5     9562
4     7175
2     5067
3     4486
1     1351
0     1090
Name: income, dtype: int64

In [82]:
X = pd.get_dummies(X, drop_first=True)
X.columns

Index(['age', 'weight', 'height', 'income', 'vegetables_day', 'fruits_day',
       'physical_ctivity', 'alcohol_day', 'sex_Male',
       'marital_status_Divorced', 'marital_status_Married',
       'marital_status_Never married', 'marital_status_Separated',
       'marital_status_Widowed', 'race_Hispanic', 'race_Multiracial',
       'race_Other race only', 'race_White only', 'education_College 4yrs',
       'education_Elementary', 'education_High School',
       'education_Junior High', 'education_No School', 'smoking_Every day',
       'smoking_Not at all', 'smoking_Some days', 'bmi_Obese',
       'bmi_Overweight', 'bmi_Underweight', 'cholestrol_Yes',
       'heart_disease_Yes', 'stroke_Yes', 'cancer_Yes', 'diabetes_Yes'],
      dtype='object')

In [83]:
print(X.shape)
print(Y.shape)

(49232, 34)
(49232, 1)

In [84]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.30, random_state=42)

In [85]:
print(X_train.shape)
print(y_train.shape)

(34462, 34)
(34462, 1)

In [86]:
from imblearn.over_sampling import SMOTE 
sm = SMOTE(random_state=20)
X_res, y_res = sm.fit_resample(X_train, y_train.values.ravel())
print(X_res.shape)
print(y_res.shape)

(40074, 34)
(40074,)

In [87]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=200)
rf = rf.fit(X_res, y_res)
rf.score(X_test, y_test)

0.6935003385240353

In [88]:
y_pred = rf.predict(X_test)

In [89]:
from sklearn.metrics import f1_score
f1_score(y_test, y_pred)

0.6218361039178013

In [90]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[6521, 1926],
       [2601, 3722]])

In [91]:
from xgboost import XGBClassifier

xgb = XGBClassifier(n_estimators=50)
xgb.fit(X_res, y_res)
print(xgb)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=50, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [92]:
print(xgb.score(X_test.to_numpy(), y_test.to_numpy()))

0.6968178740690589

In [93]:
y_pred = xgb.predict(X_test.to_numpy())

In [94]:
from sklearn.metrics import recall_score
recall_score(y_test, y_pred)

0.6278665190574094

In [95]:
from sklearn.metrics import f1_score
f1_score(y_test, y_pred)

0.639394427444033

In [96]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_true = y_test, y_pred = y_pred)

array([[6322, 2125],
       [2353, 3970]])

In [97]:
y_pred.shape

(14770,)